baseurl = "https://blog.bauzer.net/"
title = "bauzer log"
languageCode = "ja"
author = "bauzer"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
copyright = "bauzer"
canonifyurls = true

[params]
  logo      = "/images/logo.png"
  twitter   = "https://twitter.com/BAUZERMETAL"
  github    = "https://github.com/bauzer/"
  email     = "bauzerboh@gmail.com"
